#-------------------------------------------------------------
# Create Simple Deployment 
#-------------------------------------------------------------
apiVersion : apps/v1
kind: Deployment
metadata:
  name: deployment-1
  labels:
    app : my-app1
spec:
  selector:
    matchLabels:
      project: test
  template:
    metadata:
      labels:
        project: test
    spec:
      containers:
        - name : test-web
          image: torenych/my_httpd:latest
          ports:
            - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: pod-service
  labels:
    env  : test
    owner: user
spec:
  selector:
    project: test   
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 80  # Port on Load Balancer
      targetPort: 80  # Port on POD
  type: LoadBalancer

